addReviewers: true
addAssignees: author
numberOfReviewers: 1
useReviewGroups: true
reviewGroups:
  groupA:
    - k3nt0w
skipKeywords:
  - wip
filterLabels:
  include:
    - "frontend :art:"
  exclude:
    - "wip :hand:"
