export const autoUpdaterIpcMessagesOnReceived = {
  CHECK_FOR_UPDATE: '@ipc/auto-updater/RECEIVED_CHECK_FOR_UPDATE',
  UPDATE_AVAILABLE: '@ipc/auto-updater/RECEIVED_UPDATE_AVAILABLE',
  UPDATE_UNAVAILABLE: '@ipc/auto-updater/RECEIVED_UPDATE_UNAVAILABLE',
  DOWNLOAD_PROGRESS: '@ipc/auto-updater/RECEIVED_DOWNLOAD_PROGRESS',
  DOWNLOAD_PROGRESS_PERSENTAGE: '@ipc/auto-updater/RECEIVED_DOWNLOAD_PROGRESS_PERSENTAGE',
  UPDATE_DOWNLOADED: '@ipc/auto-updater/RECEIVED_UPDATE_DOWNLOADED',
  ERROR: '@ipc/auto-updater/RECEIVED_ERROR'
} as const
