name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: prepare file
        run: |
          cp dummy.firebase.admin.key.json packages/backend/firebase.admin.key.json
      - name: install deps
        run: yarn

      - name: lint
        run: yarn lint

      - name: build
        run: yarn build
