name: label checker

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled

jobs:
  checker:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: check label
        uses: actions/labeler@main
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
