name: reviewer checker

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - review_request_removed
jobs:
  checker:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: kentaro-m/auto-assign-action@v1.1.2
        with:
          configuration-path: ".github/auto-assign-backend.yml"
      - uses: kentaro-m/auto-assign-action@v1.1.2
        with:
          configuration-path: ".github/auto-assign-frontend.yml"
